import { ClerkProvider } from '@clerk/nextjs'
import './globals.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Provider from '@/components/Provider'
import HeadTag from '../components/HeadTag'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <ClerkProvider>
      <Provider>
        <html lang="en">
          <HeadTag />
          <body>{children}</body>
        </html>
      </Provider>
    </ClerkProvider>
  )
}
